### ISSUE TITLE
Is SVHN supported?

### ISSUE THREAD

**Issue by rlan** [Coderx7/SimpleNet_Pytorch#3]
```
# python3 main.py ./data/svhn.python --dataset svhn --arch simplenet --save_path ./snapshots/simplenet-svhn --epochs 540 --batch_size 100 --workers 2
save path : ./snapshots/simplenet-svhn
{'arch': 'simplenet', 'batch_size': 100, 'data_path': './data/svhn.python', 'dataset': 'svhn', 'decay': 0.002, 'epochs': 540, 'evaluate': False, 'gammas': [0.1, 0.1, 0.1, 0.1, 0.1, 0.1], 'learning_rate': 0.1, 'manualSeed': 5279, 'momentum': 0.9, 'ngpu': 1, 'print_freq': 200, 'resume': '', 'save_path': './snapshots/simplenet-svhn', 'schedule': [100, 190, 306, 390, 440, 540], 'start_epoch': 0, 'use_cuda': True, 'workers': 2}
Random Seed: 5279
python version : 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 18:21:58)  [GCC 7.2.0]
torch  version : 0.4.0
cudnn  version : 7102
Traceback (most recent call last):
  File "main.py", line 401, in <module>
    main()
  File "main.py", line 90, in main
    assert False, "Unknow dataset : {}".format(args.dataset)
AssertionError: Unknow dataset : svhn
```

**Comment by Coderx7** [comment]
Hi, the code concerning the download of the datasets is at Line [112](https://github.com/Coderx7/SimpleNet_Pytorch/blob/master/main.py#L112)  : 
```
  if args.dataset == 'cifar10':
    train_data = dset.CIFAR10(args.data_path, train=True, transform=train_transform, download=True)
    test_data = dset.CIFAR10(args.data_path, train=False, transform=test_transform, download=True)
    num_classes = 10
  elif args.dataset == 'cifar100':
    train_data = dset.CIFAR100(args.data_path, train=True, transform=train_transform, download=True)
    test_data = dset.CIFAR100(args.data_path, train=False, transform=test_transform, download=True)
    num_classes = 100
  elif args.dataset == 'imagenet':
```
As you can see only CIFAR10/100 are included. I think Pytorch has the SVHN dataset as well, but I'm not sure if it contains the whole dataset or not(I'm still new to Pytorch). Please check the documentation for that. 
I'm currently busy porting a couple of my architectures to several other frameworks when I'm done I might add other benchmarks as well.

**Comment by rlan** [comment]
@Coderx7 Thank you for the quick response. I would like to help with adding SVHN support. I see in the pytorch document that the dataset is supported (https://pytorch.org/docs/master/torchvision/datasets.html#svhn). I'm new to pytorch. Would you give me a couple of pointers as to where in your code **conceptually** would need changes. After adding a SVHN section near your previous response, I'm getting the following error:

```
==>>[2018-05-10 07:42:36] [Epoch=000/540] [Need: 00:00:00] [learning_rate=0.100000] [Best : Accuracy=0.00, Error=100.00]
Traceback (most recent call last):
  File "main.py", line 408, in <module>
    main()
  File "main.py", line 212, in main
    train_acc, train_los = train(train_loader, net, criterion, optimizer, epoch, log)
  File "main.py", line 255, in train
    for i, (input, target) in enumerate(train_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 140, in default_collate
    raise TypeError((error_msg.format(type(batch[0]))))
TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'PIL.Image.Image'>
```

**Comment by Coderx7** [comment]
you're welcome, 
it should be straight forward then, adding a new else if statement and simply doing : 
```
  elif args.dataset == 'svhn':
    train_data = dset.SVHN(args)
    test_data = dset.SVHN(args)
    num_classes = 10
```
should do the trick.

**Comment by rlan** [comment]
I added these in main.py:

```
  elif args.dataset == 'svhn':
    mean = [x / 255 for x in [129.3, 124.1, 112.4]]
    std = [x / 255 for x in [68.2, 65.4, 70.4]]
```

```
  elif args.dataset == 'svhn':
    train_data = dset.SVHN(args.data_path, split='train', transform=train_transform, download=True)
    test_data = dset.SVHN(args.data_path, split='test', transform=test_transform, download=True)
    num_classes = 10
```

Running now:

```
==>>[2018-05-10 08:12:31] [Epoch=002/540] [Need: 09:13:52] [learning_rate=0.100000] [Best : Accuracy=88.03, Error=11.97]
  Epoch: [002][000/733]   Time 0.170 (0.170)   Data 0.144 (0.144)   Loss 0.4758 (0.4758)   Prec@1 87.000 (87.000)   Prec@5 97.000 (97.000)   [2018-05-10 08:12:31]
  Epoch: [002][200/733]   Time 0.075 (0.075)   Data 0.000 (0.001)   Loss 0.4622 (0.3788)   Prec@1 86.000 (88.413)   Prec@5 99.000 (98.672)   [2018-05-10 08:12:46]
  Epoch: [002][400/733]   Time 0.079 (0.075)   Data 0.000 (0.001)   Loss 0.3337 (0.3742)   Prec@1 90.000 (88.643)   Prec@5 100.000 (98.653)   [2018-05-10 08:13:01]
  Epoch: [002][600/733]   Time 0.087 (0.075)   Data 0.000 (0.001)   Loss 0.3379 (0.3740)   Prec@1 88.000 (88.672)   Prec@5 98.000 (98.666)   [2018-05-10 08:13:16]
  **Train** Prec@1 88.725 Prec@5 98.655 Error@1 11.275
  **Test** Prec@1 90.097 Prec@5 99.251 Error@1 9.903
```

Do you have any tools to calculate the mean and std? I just copied from the existing CIFAR code.

**Comment by Coderx7** [comment]
@rlan  you shouldn't use other datasets mean/std, that's dataset/problem specific. 
if you have enough RAM you can compute the mean/std yourself, if you don't, you can search if anyone else has already done that or just don't use any mean/std. 
also, note that usually the extra+train are used for training

**Comment by rlan** [comment]
@Coderx7 Thanks for the tips. Will look

**Comment by Coderx7** [comment]
@rlan  you're welcome, again if you are trying to replicate the results in our paper, you dont need the mean/std. just scale them. and also for training use extra+train. please refer to our paper for the exact configurations concerning this. 
Best regards
